name: 'Terraform Configure'

outputs:
  environments:
    value: ${{ steps.finish.outputs.environments }}
  config:
    value: ${{ steps.finish.outputs.config }}

runs:
  using: composite
  steps:

    - id: finish
      shell: bash
      run: |
        echo "::set-output name=environments::$(cat ${D2L_TF_CONFIGURE_TMP_DIR}/envs)"
        echo "::set-output name=config::$(cat ${D2L_TF_CONFIGURE_TMP_DIR}/config)"
