name: 'Terraform Configure'

outputs:
  environments:
    value: ${{ steps.finish.outputs.environments }}
  config:
    value: ${{ steps.finish.outputs.config }}

runs:
  using: composite
  steps:

    - id: finish
      shell: bash
      run: |
        echo "environments=$(cat ${D2L_TF_CONFIGURE_TMP_DIR}/envs)" >> "$GITHUB_OUTPUT"
        echo "config=$(cat ${D2L_TF_CONFIGURE_TMP_DIR}/config)" >> "$GITHUB_OUTPUT"
