name: 'Terraform Apply'

inputs:

  config:
    description: Environment config object from terraform-workflows/collect
    required: true

runs:
  using: composite
  steps:

    - uses: Brightspace/third-party-actions@hashicorp/setup-terraform
      with:
        terraform_version: ${{ fromJson(inputs.config).terraform_version }}
        terraform_wrapper: false

    - id: download
      run: ${{ github.action_path }}/download.sh
      shell: bash
      env:
        ENVIRONMENT: ${{ fromJson(inputs.config).environment }}

    - working-directory: ${{ fromJson(inputs.config).workspace_path }}
      run: ${{ github.action_path }}/apply.sh
      shell: bash
      env:
        PLAN_PATH: ${{ steps.download.outputs.artifacts_dir }}/terraform.plan
        PLAN_ARTIFACTS: ${{ steps.download.outputs.artifacts_dir }}
        ENVIRONMENT: ${{ fromJson(inputs.config).environment }}
