name: Slack notification for Terraform Apply

inputs:
  slack_channel:
    required: true
  slack_token:
    required: true
  environment:
    required: true

runs:
  using: composite
  steps:
    - name: Send Slack notification
      env:
        GITHUB_TOKEN: ${{ github.token }}
        SLACK_CHANNEL: ${{ inputs.slack_channel }}
        SLACK_TOKEN: ${{ inputs.slack_token }}
        ENVIRONMENT: ${{ inputs.environment }}
        JOB_STATUS: ${{ job.status }}
      shell: bash
      run: "${GITHUB_ACTION_PATH}/send-apply-notification.sh"
