name: 'Terraform Configure'

inputs:

  environment:
    description: Name of the deployment / environment
    required: true

  workspace_path:
    description: Path to the terraform workspace
    required: true

  provider_role_arn_ro:
    description: Role ARN to provide as a tfvar for PRs
    required: true

  provider_role_arn_rw:
    description: Role ARN to provide as a tfvar post-merge
    required: true

  provider_role_tfvar:
    descritpion: tfvar name to use when specifying the provider role ARN
    default: 'terraform_role_arn'


runs:
  using: composite
  steps:

    - run: ${{ github.action_path }}/configure.sh
      shell: bash
      env:
        ENVCONFIG: ${{ toJson(inputs) }}
