name: 'Parse Terraform Config'

inputs:

  config:
    required: true

  max_workspaces:
    required: false
    type: number
    default: -1

outputs:
  workspaces:
    value: ${{ steps.parse.outputs.workspaces }}
  config:
    value: ${{ steps.parse.outputs.config }}

runs:
  using: composite
  steps:

    - id: parse
      run: ${{ github.action_path }}/parse.sh
      shell: bash
      env:
        HERE: ${{ github.action_path }}
        CONFIG: ${{ inputs.config }}

    - if: ${{ inputs.max_workspaces != -1 }}
      shell: bash
      run: |
        WORKSPACE_COUNT=$(jq -cr length <<< "${WORKSPACES}")
        if [ "${WORKSPACE_COUNT}" -gt "${MAX_WORKSPACES}" ]; then
          >&2 echo "This workflow supports up to ${MAX_WORKSPACES} workspaces. ${WORKSPACE_COUNT} were configured"
          exit 1
        fi
      env:
        WORKSPACES: ${{ steps.parse.outputs.workspaces }}
        MAX_WORKSPACES: ${{ inputs.max_workspaces }}
