name: 'Terraform Refresh Only'

inputs:

  config:
    description: Environment config object from terraform-workflows/workflow-refresh-only
    required: true

runs:
  using: composite
  steps:

    - uses: Brightspace/third-party-actions@hashicorp/setup-terraform
      with:
        terraform_version: ${{ fromJson(inputs.config).terraform_version }}
        terraform_wrapper: false

    - run: ${{ github.action_path }}/refresh-only.sh
      working-directory: ${{ fromJson(inputs.config).workspace_path }}
      shell: bash
      env:
        ENVIRONMENT: ${{ fromJson(inputs.config).environment }}
        PROVIDER_ROLE_TFVAR: ${{ fromJson(inputs.config).provider_role_tfvar }}
