name: 'Terraform Plan Results Collection'

outputs:

  has_changes:
    value: ${{ steps.collect.outputs.has_changes }}

  all:
    value: ${{ steps.collect.outputs.all }}

  changed:
    value: ${{ steps.collect.outputs.changed }}

  config:
    value: ${{ steps.collect.outputs.config }}

runs:
  using: composite
  steps:

    - id: setup
      shell: bash
      run: |
        echo "details_dir=$(mktemp -d)" >> "$GITHUB_OUTPUT"

    - run: ${{ github.action_path }}/download.sh
      shell: bash
      env:
        DETAILS_DIR: ${{ steps.setup.outputs.details_dir }}

    - id: collect
      run: ${{ github.action_path }}/collect.sh
      shell: bash
      env:
        DETAILS_DIR: ${{ steps.setup.outputs.details_dir }}
