name: release

on:
  push:
    tags:
      - v*.*.*

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        action:
          - apply
          - collect
          - configure
          - plan
          - script
    steps:
      - uses: Brightspace/third-party-actions@actions/checkout

      - name: Get tag details
        id: tag_details
        run: |
          TAG_NAME="${GITHUB_REF:10}"
          VERSION="${TAG_NAME}"
          MAJOR_VERSION="${VERSION%%.*}"

          echo ::set-output name=NAME::${TAG_NAME}
          echo ::set-output name=VERSION::${VERSION}
          echo ::set-output name=MAJOR_VERSION::${MAJOR_VERSION}

      - name: deploy
        env:
          FOLDER_SRC: actions/${{ matrix.action }}
          FOLDER_DEST: .dist
          TAG_SRC: ${{ steps.tag_details.outputs.NAME }}
          BRANCH: ${{ matrix.action }}/latest
          TAG_VERSION: ${{ matrix.action }}/${{ steps.tag_details.outputs.VERSION }}
          TAG_MAJOR_VERSION: ${{ matrix.action }}/${{ steps.tag_details.outputs.MAJOR_VERSION }}
        run: |
          git fetch --depth=1 origin "${BRANCH}"

          git worktree add "${FOLDER_DEST}" "${BRANCH}"
          rm -r "${FOLDER_DEST}"/* || :

          MESSAGE=$(git tag -l "${TAG_SRC}" --format='%(subject)

          %(body)' | sed -n '/-----BEGIN PGP SIGNATURE-----/q;p')

          cp -rT "${FOLDER_SRC}" "${FOLDER_DEST}"
          cd "${FOLDER_DEST}"
          git add .

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git commit --allow-empty -m "${MESSAGE}"
          git tag "${TAG_VERSION}" -m "${MESSAGE}"
          git tag -f "${TAG_MAJOR_VERSION}" -m "${MESSAGE}"
          git push -f origin "${BRANCH}" "${TAG_VERSION}" "${TAG_MAJOR_VERSION}"



