name: Terraform

on:
  workflow_call:
    inputs:
      comment_plan:
        description: Create a pull request comment of the plan in addition to adding it to the summary page
        required: false
        type: boolean
        default: true

      config:
        description: A JSON (with comments) config string
        required: true
        type: string

      default_branch:
        required: false
        type: string
        default: main

      refresh_on_pr:
        required: false
        type: boolean
        default: true

      terraform_version:
        required: true
        type: string

      apply_timeout:
        required: false
        default: 60
        type: number

      require_lockfile:
        description: Fail the workflow if the .terraform.lock.hcl file doesn't declare all providers in the workspace
        required: false
        type: boolean
        default: false

      artifacts_url:
        description: Download an archive from the specified url and extract it under .artifacts in the root of the workspace
        required: false
        type: string
        default: ""

      artifact_repositories:
        description: |
          Configuration for additional GitHub repositories of artifacts to be downloaded into the workspace.
          Each repository can be referenced as ${path.root}/.artifacts/artifact_repositories/{slug}/{ref}.
          Supports passing up to 5 token secrets for authorizing the downloads
        required: false
        type: string

    outputs:
      had_changes:
        value: ${{ toJson(jobs.plan_apply.outputs.*) != '[]' }}

    secrets:
      ARTIFACT_REPOSITORIES_SECRET_1:
        required: false
      ARTIFACT_REPOSITORIES_SECRET_2:
        required: false
      ARTIFACT_REPOSITORIES_SECRET_3:
        required: false
      ARTIFACT_REPOSITORIES_SECRET_4:
        required: false
      ARTIFACT_REPOSITORIES_SECRET_5:
        required: false

jobs:
  plan_apply:
    name: Plan and Apply (${{ matrix.key || matrix.environment }})
    runs-on: [self-hosted, Linux, AWS]
    timeout-minutes: 60

    permissions:
      contents: read
      id-token: write
      pull-requests: write

    environment: ${{ github.event_name != 'pull_request' && matrix.environment || null }}
    # Workflows against a branch run one-at-a-time, workflows against a PR are non-blocking
    concurrency: ${{ matrix.key || matrix.environment }}/${{ github.event_name != 'pull_request' && github.ref || github.run_id }}

    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(inputs.config).*.workspaces.* }}

    steps:
    - id: parse
      uses: Brightspace/terraform-workflows/actions/parse-config@v5
      with:
        # GHA's fromJson() supports comments in JSON strings which is nice from
        # an end-user perspective (e.g. naming account ids). toJson(fromJson())
        # is used in order to strip these comments out before parsing it ourselves
        config: ${{ toJson(fromJson(inputs.config)) }}
        max_workspaces: 50

    - uses: Brightspace/third-party-actions@actions/checkout

    - if: ${{ github.event_name != 'pull_request' }}
      name: 'Assert: Branch is up to date'
      uses: Brightspace/assert-git-remote-ref-action@main
      with:
        remote: origin
        ref: ${{ inputs.default_branch }}

    - if: ${{ inputs.artifacts_url != '' }}
      name: 'Extract artifacts'
      uses: Brightspace/s3-artifact-actions/extract@main
      with:
        path: ${{ fromJson(steps.parse.outputs.config)[matrix.key || matrix.environment].workspace_path }}/.artifacts
        artifacts_url: ${{ inputs.artifacts_url }}

    - if: ${{ inputs.artifact_repositories != '' }}
      name: Download artifact repositories
      uses: Brightspace/terraform-workflows/actions/plan/artifact-repositories@v5
      with:
        artifacts_dir: ${{ fromJson(steps.parse.outputs.config)[matrix.key || matrix.environment].workspace_path }}/.artifacts
        config: ${{ inputs.artifact_repositories }}
      env:
        ARTIFACT_REPOSITORIES_SECRET_1: ${{ secrets.ARTIFACT_REPOSITORIES_SECRET_1 }}
        ARTIFACT_REPOSITORIES_SECRET_2: ${{ secrets.ARTIFACT_REPOSITORIES_SECRET_2 }}
        ARTIFACT_REPOSITORIES_SECRET_3: ${{ secrets.ARTIFACT_REPOSITORIES_SECRET_3 }}
        ARTIFACT_REPOSITORIES_SECRET_4: ${{ secrets.ARTIFACT_REPOSITORIES_SECRET_4 }}
        ARTIFACT_REPOSITORIES_SECRET_5: ${{ secrets.ARTIFACT_REPOSITORIES_SECRET_5 }}

    - if: ${{ github.event_name == 'pull_request' }}
      name: Assume Hub Role (PR)
      uses: Brightspace/third-party-actions@aws-actions/configure-aws-credentials
      with:
        role-to-assume: arn:aws:iam::323258989788:role/hub-roles/github+${{ github.repository_owner }}+${{ github.event.repository.name }}+repo
        aws-region: us-east-1

    - if: ${{ github.event_name != 'pull_request' }}
      name: Assume Hub Role
      uses: Brightspace/third-party-actions@aws-actions/configure-aws-credentials
      with:
        role-to-assume: arn:aws:iam::323258989788:role/hub-roles/github+${{ github.repository_owner }}+${{ github.event.repository.name }}+tfapply
        aws-region: us-east-1

    - id: plan
      uses: Brightspace/terraform-workflows/actions/plan@v5
      with:
        comment_plan: ${{ inputs.comment_plan }}
        config: ${{ toJson(fromJson(steps.parse.outputs.config)[matrix.key || matrix.environment]) }}
        terraform_version: ${{ inputs.terraform_version }}
        refresh_on_pr: ${{ inputs.refresh_on_pr }}
        require_lockfile: ${{ inputs.require_lockfile }}
        skip_archive: true

    # Matrixed jobs overwrite eachother's outputs if they use the same name.
    # Unfortunately though, job outputs need to be statically defined in the yml
    # Step outputs are dynamic though, as well as the _population_ of job outputs
    # (based on the existence of their configured value). This step uniquely maps
    # the workspace key to one of the statically defined outputs below. The
    # apply step can then consume the sparse set of outputs that were assigned a
    # value via `needs.plan_apply.outputs.*`
    - if: ${{ github.event_name != 'pull_request' && steps.plan.outputs.has_changes == 'true' }}
      name: Mark as changed
      id: changed
      shell: bash
      run: |
        WORKSPACE_INDEX=$(jq -cr \
          --arg workspace_key "${WORKSPACE_KEY}" \
          '
            to_entries[]
            | select(.value == $workspace_key)
            | .key
          ' \
          <<< "${WORKSPACES}"
        )
        echo "changed_workspace_${WORKSPACE_INDEX}=${WORKSPACE_KEY}" >> "${GITHUB_OUTPUT}"
      env:
        WORKSPACES: ${{ steps.parse.outputs.workspaces }}
        WORKSPACE_KEY: ${{ matrix.key || matrix.environment }}

    - if: github.event_name != 'pull_request' && steps.plan.outputs.has_changes == 'true'
      name: Apply
      working-directory: ${{ fromJson(steps.parse.outputs.config)[matrix.key || matrix.environment].workspace_path }}
      shell: bash
      run: |
        terraform apply -input=false "${PLAN_PATH}"
      env:
        PLAN_PATH: ${{ steps.plan.outputs.plan_path }}

    outputs:
      changed_workspace_0: ${{ steps.changed.outputs.changed_workspace_0 }}
      changed_workspace_1: ${{ steps.changed.outputs.changed_workspace_1 }}
      changed_workspace_2: ${{ steps.changed.outputs.changed_workspace_2 }}
      changed_workspace_3: ${{ steps.changed.outputs.changed_workspace_3 }}
      changed_workspace_4: ${{ steps.changed.outputs.changed_workspace_4 }}
      changed_workspace_5: ${{ steps.changed.outputs.changed_workspace_5 }}
      changed_workspace_6: ${{ steps.changed.outputs.changed_workspace_6 }}
      changed_workspace_7: ${{ steps.changed.outputs.changed_workspace_7 }}
      changed_workspace_8: ${{ steps.changed.outputs.changed_workspace_8 }}
      changed_workspace_9: ${{ steps.changed.outputs.changed_workspace_9 }}
      changed_workspace_10: ${{ steps.changed.outputs.changed_workspace_10 }}
      changed_workspace_11: ${{ steps.changed.outputs.changed_workspace_11 }}
      changed_workspace_12: ${{ steps.changed.outputs.changed_workspace_12 }}
      changed_workspace_13: ${{ steps.changed.outputs.changed_workspace_13 }}
      changed_workspace_14: ${{ steps.changed.outputs.changed_workspace_14 }}
      changed_workspace_15: ${{ steps.changed.outputs.changed_workspace_15 }}
      changed_workspace_16: ${{ steps.changed.outputs.changed_workspace_16 }}
      changed_workspace_17: ${{ steps.changed.outputs.changed_workspace_17 }}
      changed_workspace_18: ${{ steps.changed.outputs.changed_workspace_18 }}
      changed_workspace_19: ${{ steps.changed.outputs.changed_workspace_19 }}
      changed_workspace_20: ${{ steps.changed.outputs.changed_workspace_20 }}
      changed_workspace_21: ${{ steps.changed.outputs.changed_workspace_21 }}
      changed_workspace_22: ${{ steps.changed.outputs.changed_workspace_22 }}
      changed_workspace_23: ${{ steps.changed.outputs.changed_workspace_23 }}
      changed_workspace_24: ${{ steps.changed.outputs.changed_workspace_24 }}
      changed_workspace_25: ${{ steps.changed.outputs.changed_workspace_25 }}
      changed_workspace_26: ${{ steps.changed.outputs.changed_workspace_26 }}
      changed_workspace_27: ${{ steps.changed.outputs.changed_workspace_27 }}
      changed_workspace_28: ${{ steps.changed.outputs.changed_workspace_28 }}
      changed_workspace_29: ${{ steps.changed.outputs.changed_workspace_29 }}
      changed_workspace_30: ${{ steps.changed.outputs.changed_workspace_30 }}
      changed_workspace_31: ${{ steps.changed.outputs.changed_workspace_31 }}
      changed_workspace_32: ${{ steps.changed.outputs.changed_workspace_32 }}
      changed_workspace_33: ${{ steps.changed.outputs.changed_workspace_33 }}
      changed_workspace_34: ${{ steps.changed.outputs.changed_workspace_34 }}
      changed_workspace_35: ${{ steps.changed.outputs.changed_workspace_35 }}
      changed_workspace_36: ${{ steps.changed.outputs.changed_workspace_36 }}
      changed_workspace_37: ${{ steps.changed.outputs.changed_workspace_37 }}
      changed_workspace_38: ${{ steps.changed.outputs.changed_workspace_38 }}
      changed_workspace_39: ${{ steps.changed.outputs.changed_workspace_39 }}
      changed_workspace_40: ${{ steps.changed.outputs.changed_workspace_40 }}
      changed_workspace_41: ${{ steps.changed.outputs.changed_workspace_41 }}
      changed_workspace_42: ${{ steps.changed.outputs.changed_workspace_42 }}
      changed_workspace_43: ${{ steps.changed.outputs.changed_workspace_43 }}
      changed_workspace_44: ${{ steps.changed.outputs.changed_workspace_44 }}
      changed_workspace_45: ${{ steps.changed.outputs.changed_workspace_45 }}
      changed_workspace_46: ${{ steps.changed.outputs.changed_workspace_46 }}
      changed_workspace_47: ${{ steps.changed.outputs.changed_workspace_47 }}
      changed_workspace_48: ${{ steps.changed.outputs.changed_workspace_48 }}
      changed_workspace_49: ${{ steps.changed.outputs.changed_workspace_49 }}
