name: Terraform

on:
  workflow_call:
    inputs:
      comment_plan:
        description: Create a pull request comment of the plan in addition to adding it to the summary page
        required: false
        type: boolean
        default: true

      config:
        required: true
        type: string

      default_branch:
        required: false
        type: string
        default: main

      refresh_on_pr:
        required: false
        type: boolean
        default: true

      terraform_version:
        required: true
        type: string

      apply_timeout:
        required: false
        default: 60
        type: number

      artifacts_url:
        description: Download an archive from the specified url and extract it under .artifacts in the root of the workspace
        required: false
        type: string
        default: ""

    outputs:
      had_changes:
        value: ${{ toJson(jobs.plan.outputs.*) != '[]' }}

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

jobs:
  configure:
    name: Configure
    runs-on: [self-hosted, Linux, AWS]
    timeout-minutes: 10

    steps:
      - id: parse
        uses: Brightspace/terraform-workflows/actions/configure/parse@v3
        with:
          config: ${{ inputs.config }}
          max_environments: 50

    outputs:
      environments: ${{ steps.parse.outputs.environments }}
      config: ${{ steps.parse.outputs.config }}


  plan:
    name: Plan
    runs-on: [self-hosted, Linux, AWS]
    timeout-minutes: 60

    environment: ${{ github.event_name != 'pull_request' && 'preflight' || null }}

    needs: configure

    strategy:
      fail-fast: false
      matrix:
        environment: ${{ fromJson(needs.configure.outputs.environments) }}

    steps:
    - uses: Brightspace/third-party-actions@actions/checkout

    - if: ${{ github.event_name != 'pull_request' }}
      name: 'Assert: Branch is up to date'
      uses: Brightspace/assert-git-remote-ref-action@main
      with:
        remote: origin
        ref: ${{ inputs.default_branch }}

    - if: ${{ inputs.artifacts_url != '' }}
      name: 'Extract artifacts'
      uses: Brightspace/s3-artifact-actions/extract@master
      with:
        path: ${{ fromJson(needs.configure.outputs.config)[matrix.environment].workspace_path }}/.artifacts
        artifacts_url: ${{ inputs.artifacts_url }}

    - id: plan
      uses: Brightspace/terraform-workflows/actions/plan@v3
      with:
        comment_plan: ${{ inputs.comment_plan }}
        config: ${{ toJson(fromJson(needs.configure.outputs.config)[matrix.environment]) }}
        terraform_version: ${{ inputs.terraform_version }}
        refresh_on_pr: ${{ inputs.refresh_on_pr }}

    - if: ${{ steps.plan.outputs.has_changes == 'true' }}
      name: Mark as changed
      id: changed
      shell: bash
      run: |
        ENVIRONMENT_INDEX=$(jq -cr \
          --arg environment "${ENVIRONMENT}" \
          '
            to_entries[]
            | select(.value == $environment)
            | .key
          ' \
          <<< "${ENVIRONMENTS}"
        )
        echo "changed_env_${ENVIRONMENT_INDEX}=${ENVIRONMENT}" >> "${GITHUB_OUTPUT}"
      env:
        ENVIRONMENTS: ${{ needs.configure.outputs.environments }}
        ENVIRONMENT: ${{ matrix.environment }}

    outputs:
      changed_env_0: ${{ steps.changed.outputs.changed_env_0 }}
      changed_env_1: ${{ steps.changed.outputs.changed_env_1 }}
      changed_env_2: ${{ steps.changed.outputs.changed_env_2 }}
      changed_env_3: ${{ steps.changed.outputs.changed_env_3 }}
      changed_env_4: ${{ steps.changed.outputs.changed_env_4 }}
      changed_env_5: ${{ steps.changed.outputs.changed_env_5 }}
      changed_env_6: ${{ steps.changed.outputs.changed_env_6 }}
      changed_env_7: ${{ steps.changed.outputs.changed_env_7 }}
      changed_env_8: ${{ steps.changed.outputs.changed_env_8 }}
      changed_env_9: ${{ steps.changed.outputs.changed_env_9 }}
      changed_env_10: ${{ steps.changed.outputs.changed_env_10 }}
      changed_env_11: ${{ steps.changed.outputs.changed_env_11 }}
      changed_env_12: ${{ steps.changed.outputs.changed_env_12 }}
      changed_env_13: ${{ steps.changed.outputs.changed_env_13 }}
      changed_env_14: ${{ steps.changed.outputs.changed_env_14 }}
      changed_env_15: ${{ steps.changed.outputs.changed_env_15 }}
      changed_env_16: ${{ steps.changed.outputs.changed_env_16 }}
      changed_env_17: ${{ steps.changed.outputs.changed_env_17 }}
      changed_env_18: ${{ steps.changed.outputs.changed_env_18 }}
      changed_env_19: ${{ steps.changed.outputs.changed_env_19 }}
      changed_env_20: ${{ steps.changed.outputs.changed_env_20 }}
      changed_env_21: ${{ steps.changed.outputs.changed_env_21 }}
      changed_env_22: ${{ steps.changed.outputs.changed_env_22 }}
      changed_env_23: ${{ steps.changed.outputs.changed_env_23 }}
      changed_env_24: ${{ steps.changed.outputs.changed_env_24 }}
      changed_env_25: ${{ steps.changed.outputs.changed_env_25 }}
      changed_env_26: ${{ steps.changed.outputs.changed_env_26 }}
      changed_env_27: ${{ steps.changed.outputs.changed_env_27 }}
      changed_env_28: ${{ steps.changed.outputs.changed_env_28 }}
      changed_env_29: ${{ steps.changed.outputs.changed_env_29 }}
      changed_env_30: ${{ steps.changed.outputs.changed_env_30 }}
      changed_env_31: ${{ steps.changed.outputs.changed_env_31 }}
      changed_env_32: ${{ steps.changed.outputs.changed_env_32 }}
      changed_env_33: ${{ steps.changed.outputs.changed_env_33 }}
      changed_env_34: ${{ steps.changed.outputs.changed_env_34 }}
      changed_env_35: ${{ steps.changed.outputs.changed_env_35 }}
      changed_env_36: ${{ steps.changed.outputs.changed_env_36 }}
      changed_env_37: ${{ steps.changed.outputs.changed_env_37 }}
      changed_env_38: ${{ steps.changed.outputs.changed_env_38 }}
      changed_env_39: ${{ steps.changed.outputs.changed_env_39 }}
      changed_env_40: ${{ steps.changed.outputs.changed_env_40 }}
      changed_env_41: ${{ steps.changed.outputs.changed_env_41 }}
      changed_env_42: ${{ steps.changed.outputs.changed_env_42 }}
      changed_env_43: ${{ steps.changed.outputs.changed_env_43 }}
      changed_env_44: ${{ steps.changed.outputs.changed_env_44 }}
      changed_env_45: ${{ steps.changed.outputs.changed_env_45 }}
      changed_env_46: ${{ steps.changed.outputs.changed_env_46 }}
      changed_env_47: ${{ steps.changed.outputs.changed_env_47 }}
      changed_env_48: ${{ steps.changed.outputs.changed_env_48 }}
      changed_env_49: ${{ steps.changed.outputs.changed_env_49 }}

  apply:
    name: Apply
    runs-on: [self-hosted, Linux, AWS]
    timeout-minutes: ${{ inputs.apply_timeout }}

    needs: [configure, plan]

    if: ${{ github.event_name != 'pull_request' && toJson(needs.plan.outputs.*) != '[]' }}

    strategy:
      fail-fast: false
      matrix:
        environment: ${{ needs.plan.outputs.* }}

    environment: ${{ matrix.environment }}
    concurrency: ${{ matrix.environment }}

    steps:
    - uses: Brightspace/third-party-actions@actions/checkout

    - uses: Brightspace/terraform-workflows/actions/apply@v3
      with:
        config: |
          {
            "terraform_version": "${{ inputs.terraform_version }}",
            "environment": "${{ matrix.environment }}",
            "workspace_path": "${{ fromJson(needs.configure.outputs.config)[matrix.environment].workspace_path }}"
          }
