name: Terraform

on:
  workflow_call:
    inputs:
      comment_plan:
        description: Create a pull request comment of the plan in addition to adding it to the summary page
        required: false
        type: boolean
        default: true

      config:
        description: A JSON (with comments) config string
        required: true
        type: string

      default_branch:
        required: false
        type: string
        default: main

      refresh_on_pr:
        required: false
        type: boolean
        default: true

      terraform_version:
        required: true
        type: string

      apply_timeout:
        required: false
        default: 60
        type: number

      require_lockfile:
        description: Fail the workflow if the .terraform.lock.hcl file doesn't declare all providers in the workspace
        required: false
        type: boolean
        default: false

      artifacts_url:
        description: Download an archive from the specified url and extract it under .artifacts in the root of the workspace
        required: false
        type: string
        default: ""

      artifact_repositories:
        description: |
          Configuration for additional GitHub repositories of artifacts to be downloaded into the workspace.
          Each repository can be referenced as ${path.root}/.artifacts/artifact_repositories/{slug}/{ref}.
          Supports passing up to 5 token secrets for authorizing the downloads
        required: false
        type: string

      slack_channel:
        description: The Slack channel to send notifications to
        required: false
        type: string
        default: ""

    outputs:
      had_changes:
        value: ${{ toJson(jobs.plan.outputs.*) != '[]' }}

    secrets:
      ARTIFACT_REPOSITORIES_SECRET_1:
        required: false
      ARTIFACT_REPOSITORIES_SECRET_2:
        required: false
      ARTIFACT_REPOSITORIES_SECRET_3:
        required: false
      ARTIFACT_REPOSITORIES_SECRET_4:
        required: false
      ARTIFACT_REPOSITORIES_SECRET_5:
        required: false
      D2L_SLACK_TOKEN:
        required: false

jobs:
  plan:
    name: Plan (${{ matrix.key || matrix.environment }})
    runs-on: [self-hosted, Linux, AWS]
    timeout-minutes: 60

    permissions:
      actions: read
      contents: read
      id-token: write
      pull-requests: write

    environment: ${{ github.event_name != 'pull_request' && 'preflight' || null }}

    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(inputs.config).*.workspaces.* }}

    steps:
    - id: parse
      uses: Brightspace/terraform-workflows/actions/parse-config@v4
      with:
        # GHA's fromJson() supports comments in JSON strings which is nice from
        # an end-user perspective (e.g. naming account ids). toJson(fromJson())
        # is used in order to strip these comments out before parsing it ourselves
        config: ${{ toJson(fromJson(inputs.config)) }}
        max_workspaces: 200

    - uses: Brightspace/third-party-actions@actions/checkout

    # - if: ${{ github.event_name != 'pull_request' }}
    #   name: 'Assert: Branch is up to date'
    #   uses: Brightspace/assert-git-remote-ref-action@main
    #   with:
    #     remote: origin
    #     ref: ${{ inputs.default_branch }}

    - if: ${{ inputs.artifacts_url != '' }}
      name: 'Extract artifacts'
      uses: Brightspace/s3-artifact-actions/extract@main
      with:
        path: ${{ fromJson(steps.parse.outputs.config)[matrix.key || matrix.environment].workspace_path }}/.artifacts
        artifacts_url: ${{ inputs.artifacts_url }}

    - if: ${{ inputs.artifact_repositories != '' }}
      name: Download artifact repositories
      uses: Brightspace/terraform-workflows/actions/plan/artifact-repositories@v4
      with:
        artifacts_dir: ${{ fromJson(steps.parse.outputs.config)[matrix.key || matrix.environment].workspace_path }}/.artifacts
        config: ${{ inputs.artifact_repositories }}
      env:
        ARTIFACT_REPOSITORIES_SECRET_1: ${{ secrets.ARTIFACT_REPOSITORIES_SECRET_1 }}
        ARTIFACT_REPOSITORIES_SECRET_2: ${{ secrets.ARTIFACT_REPOSITORIES_SECRET_2 }}
        ARTIFACT_REPOSITORIES_SECRET_3: ${{ secrets.ARTIFACT_REPOSITORIES_SECRET_3 }}
        ARTIFACT_REPOSITORIES_SECRET_4: ${{ secrets.ARTIFACT_REPOSITORIES_SECRET_4 }}
        ARTIFACT_REPOSITORIES_SECRET_5: ${{ secrets.ARTIFACT_REPOSITORIES_SECRET_5 }}

    - if: ${{ github.event_name == 'pull_request' }}
      name: Assume Hub Role (PR)
      uses: Brightspace/third-party-actions@aws-actions/configure-aws-credentials
      with:
        role-to-assume: arn:aws:iam::323258989788:role/hub-roles/github+${{ github.repository_owner }}+${{ github.event.repository.name }}+repo
        aws-region: us-east-1

    - if: ${{ github.event_name != 'pull_request' }}
      name: Assume Hub Role
      uses: Brightspace/third-party-actions@aws-actions/configure-aws-credentials
      with:
        role-to-assume: arn:aws:iam::323258989788:role/hub-roles/github+${{ github.repository_owner }}+${{ github.event.repository.name }}+tfapply
        aws-region: us-east-1

    - id: plan
      uses: Brightspace/terraform-workflows/actions/plan@v4
      with:
        comment_plan: ${{ inputs.comment_plan }}
        config: ${{ toJson(fromJson(steps.parse.outputs.config)[matrix.key || matrix.environment]) }}
        terraform_version: ${{ inputs.terraform_version }}
        refresh_on_pr: ${{ inputs.refresh_on_pr }}
        require_lockfile: ${{ inputs.require_lockfile }}

    - if: ${{ github.event_name != 'pull_request' && steps.plan.outputs.has_changes == 'true' && inputs.slack_channel != '' }}
      continue-on-error: true
      name: Send Slack notification
      uses: Brightspace/terraform-workflows/actions/plan/slack@v4
      with:
        slack_channel: ${{ inputs.slack_channel }}
        slack_token: ${{ secrets.D2L_SLACK_TOKEN }}
        workspace_key: ${{ matrix.key || matrix.environment }}

    # Matrixed jobs overwrite eachother's outputs if they use the same name.
    # Unfortunately though, job outputs need to be statically defined in the yml
    # Step outputs are dynamic though, as well as the _population_ of job outputs
    # (based on the existence of their configured value). This step uniquely maps
    # the workspace key to one of the statically defined outputs below. The
    # apply job can then consume the sparse set of outputs that were assigned a
    # value via `needs.plan.outputs.*`
    - if: ${{ github.event_name != 'pull_request' && steps.plan.outputs.has_changes == 'true' }}
      name: Mark as changed
      id: changed
      shell: bash
      run: |
        WORKSPACE_INDEX=$(jq -cr \
          --arg workspace_key "${WORKSPACE_KEY}" \
          '
            to_entries[]
            | select(.value == $workspace_key)
            | .key
          ' \
          <<< "${WORKSPACES}"
        )
        CHANGED=$(jq -cn --arg key "${WORKSPACE_KEY}" --arg environment "${ENVIRONMENT}" '{key:$key,environment:$environment}')
        echo "changed_workspace_${WORKSPACE_INDEX}=${CHANGED}" >> "${GITHUB_OUTPUT}"
      env:
        WORKSPACES: ${{ steps.parse.outputs.workspaces }}
        WORKSPACE_KEY: ${{ matrix.key || matrix.environment }}
        ENVIRONMENT: ${{ matrix.environment }}

    outputs:
      changed_workspace_0: ${{ steps.changed.outputs.changed_workspace_0 }}
      changed_workspace_1: ${{ steps.changed.outputs.changed_workspace_1 }}
      changed_workspace_2: ${{ steps.changed.outputs.changed_workspace_2 }}
      changed_workspace_3: ${{ steps.changed.outputs.changed_workspace_3 }}
      changed_workspace_4: ${{ steps.changed.outputs.changed_workspace_4 }}
      changed_workspace_5: ${{ steps.changed.outputs.changed_workspace_5 }}
      changed_workspace_6: ${{ steps.changed.outputs.changed_workspace_6 }}
      changed_workspace_7: ${{ steps.changed.outputs.changed_workspace_7 }}
      changed_workspace_8: ${{ steps.changed.outputs.changed_workspace_8 }}
      changed_workspace_9: ${{ steps.changed.outputs.changed_workspace_9 }}
      changed_workspace_10: ${{ steps.changed.outputs.changed_workspace_10 }}
      changed_workspace_11: ${{ steps.changed.outputs.changed_workspace_11 }}
      changed_workspace_12: ${{ steps.changed.outputs.changed_workspace_12 }}
      changed_workspace_13: ${{ steps.changed.outputs.changed_workspace_13 }}
      changed_workspace_14: ${{ steps.changed.outputs.changed_workspace_14 }}
      changed_workspace_15: ${{ steps.changed.outputs.changed_workspace_15 }}
      changed_workspace_16: ${{ steps.changed.outputs.changed_workspace_16 }}
      changed_workspace_17: ${{ steps.changed.outputs.changed_workspace_17 }}
      changed_workspace_18: ${{ steps.changed.outputs.changed_workspace_18 }}
      changed_workspace_19: ${{ steps.changed.outputs.changed_workspace_19 }}
      changed_workspace_20: ${{ steps.changed.outputs.changed_workspace_20 }}
      changed_workspace_21: ${{ steps.changed.outputs.changed_workspace_21 }}
      changed_workspace_22: ${{ steps.changed.outputs.changed_workspace_22 }}
      changed_workspace_23: ${{ steps.changed.outputs.changed_workspace_23 }}
      changed_workspace_24: ${{ steps.changed.outputs.changed_workspace_24 }}
      changed_workspace_25: ${{ steps.changed.outputs.changed_workspace_25 }}
      changed_workspace_26: ${{ steps.changed.outputs.changed_workspace_26 }}
      changed_workspace_27: ${{ steps.changed.outputs.changed_workspace_27 }}
      changed_workspace_28: ${{ steps.changed.outputs.changed_workspace_28 }}
      changed_workspace_29: ${{ steps.changed.outputs.changed_workspace_29 }}
      changed_workspace_30: ${{ steps.changed.outputs.changed_workspace_30 }}
      changed_workspace_31: ${{ steps.changed.outputs.changed_workspace_31 }}
      changed_workspace_32: ${{ steps.changed.outputs.changed_workspace_32 }}
      changed_workspace_33: ${{ steps.changed.outputs.changed_workspace_33 }}
      changed_workspace_34: ${{ steps.changed.outputs.changed_workspace_34 }}
      changed_workspace_35: ${{ steps.changed.outputs.changed_workspace_35 }}
      changed_workspace_36: ${{ steps.changed.outputs.changed_workspace_36 }}
      changed_workspace_37: ${{ steps.changed.outputs.changed_workspace_37 }}
      changed_workspace_38: ${{ steps.changed.outputs.changed_workspace_38 }}
      changed_workspace_39: ${{ steps.changed.outputs.changed_workspace_39 }}
      changed_workspace_40: ${{ steps.changed.outputs.changed_workspace_40 }}
      changed_workspace_41: ${{ steps.changed.outputs.changed_workspace_41 }}
      changed_workspace_42: ${{ steps.changed.outputs.changed_workspace_42 }}
      changed_workspace_43: ${{ steps.changed.outputs.changed_workspace_43 }}
      changed_workspace_44: ${{ steps.changed.outputs.changed_workspace_44 }}
      changed_workspace_45: ${{ steps.changed.outputs.changed_workspace_45 }}
      changed_workspace_46: ${{ steps.changed.outputs.changed_workspace_46 }}
      changed_workspace_47: ${{ steps.changed.outputs.changed_workspace_47 }}
      changed_workspace_48: ${{ steps.changed.outputs.changed_workspace_48 }}
      changed_workspace_49: ${{ steps.changed.outputs.changed_workspace_49 }}
      changed_workspace_50: ${{ steps.changed.outputs.changed_workspace_50 }}
      changed_workspace_51: ${{ steps.changed.outputs.changed_workspace_51 }}
      changed_workspace_52: ${{ steps.changed.outputs.changed_workspace_52 }}
      changed_workspace_53: ${{ steps.changed.outputs.changed_workspace_53 }}
      changed_workspace_54: ${{ steps.changed.outputs.changed_workspace_54 }}
      changed_workspace_55: ${{ steps.changed.outputs.changed_workspace_55 }}
      changed_workspace_56: ${{ steps.changed.outputs.changed_workspace_56 }}
      changed_workspace_57: ${{ steps.changed.outputs.changed_workspace_57 }}
      changed_workspace_58: ${{ steps.changed.outputs.changed_workspace_58 }}
      changed_workspace_59: ${{ steps.changed.outputs.changed_workspace_59 }}
      changed_workspace_60: ${{ steps.changed.outputs.changed_workspace_60 }}
      changed_workspace_61: ${{ steps.changed.outputs.changed_workspace_61 }}
      changed_workspace_62: ${{ steps.changed.outputs.changed_workspace_62 }}
      changed_workspace_63: ${{ steps.changed.outputs.changed_workspace_63 }}
      changed_workspace_64: ${{ steps.changed.outputs.changed_workspace_64 }}
      changed_workspace_65: ${{ steps.changed.outputs.changed_workspace_65 }}
      changed_workspace_66: ${{ steps.changed.outputs.changed_workspace_66 }}
      changed_workspace_67: ${{ steps.changed.outputs.changed_workspace_67 }}
      changed_workspace_68: ${{ steps.changed.outputs.changed_workspace_68 }}
      changed_workspace_69: ${{ steps.changed.outputs.changed_workspace_69 }}
      changed_workspace_70: ${{ steps.changed.outputs.changed_workspace_70 }}
      changed_workspace_71: ${{ steps.changed.outputs.changed_workspace_71 }}
      changed_workspace_72: ${{ steps.changed.outputs.changed_workspace_72 }}
      changed_workspace_73: ${{ steps.changed.outputs.changed_workspace_73 }}
      changed_workspace_74: ${{ steps.changed.outputs.changed_workspace_74 }}
      changed_workspace_75: ${{ steps.changed.outputs.changed_workspace_75 }}
      changed_workspace_76: ${{ steps.changed.outputs.changed_workspace_76 }}
      changed_workspace_77: ${{ steps.changed.outputs.changed_workspace_77 }}
      changed_workspace_78: ${{ steps.changed.outputs.changed_workspace_78 }}
      changed_workspace_79: ${{ steps.changed.outputs.changed_workspace_79 }}
      changed_workspace_80: ${{ steps.changed.outputs.changed_workspace_80 }}
      changed_workspace_81: ${{ steps.changed.outputs.changed_workspace_81 }}
      changed_workspace_82: ${{ steps.changed.outputs.changed_workspace_82 }}
      changed_workspace_83: ${{ steps.changed.outputs.changed_workspace_83 }}
      changed_workspace_84: ${{ steps.changed.outputs.changed_workspace_84 }}
      changed_workspace_85: ${{ steps.changed.outputs.changed_workspace_85 }}
      changed_workspace_86: ${{ steps.changed.outputs.changed_workspace_86 }}
      changed_workspace_87: ${{ steps.changed.outputs.changed_workspace_87 }}
      changed_workspace_88: ${{ steps.changed.outputs.changed_workspace_88 }}
      changed_workspace_89: ${{ steps.changed.outputs.changed_workspace_89 }}
      changed_workspace_90: ${{ steps.changed.outputs.changed_workspace_90 }}
      changed_workspace_91: ${{ steps.changed.outputs.changed_workspace_91 }}
      changed_workspace_92: ${{ steps.changed.outputs.changed_workspace_92 }}
      changed_workspace_93: ${{ steps.changed.outputs.changed_workspace_93 }}
      changed_workspace_94: ${{ steps.changed.outputs.changed_workspace_94 }}
      changed_workspace_95: ${{ steps.changed.outputs.changed_workspace_95 }}
      changed_workspace_96: ${{ steps.changed.outputs.changed_workspace_96 }}
      changed_workspace_97: ${{ steps.changed.outputs.changed_workspace_97 }}
      changed_workspace_98: ${{ steps.changed.outputs.changed_workspace_98 }}
      changed_workspace_99: ${{ steps.changed.outputs.changed_workspace_99 }}
      changed_workspace_100: ${{ steps.changed.outputs.changed_workspace_100 }}
      changed_workspace_101: ${{ steps.changed.outputs.changed_workspace_101 }}
      changed_workspace_102: ${{ steps.changed.outputs.changed_workspace_102 }}
      changed_workspace_103: ${{ steps.changed.outputs.changed_workspace_103 }}
      changed_workspace_104: ${{ steps.changed.outputs.changed_workspace_104 }}
      changed_workspace_105: ${{ steps.changed.outputs.changed_workspace_105 }}
      changed_workspace_106: ${{ steps.changed.outputs.changed_workspace_106 }}
      changed_workspace_107: ${{ steps.changed.outputs.changed_workspace_107 }}
      changed_workspace_108: ${{ steps.changed.outputs.changed_workspace_108 }}
      changed_workspace_109: ${{ steps.changed.outputs.changed_workspace_109 }}
      changed_workspace_110: ${{ steps.changed.outputs.changed_workspace_110 }}
      changed_workspace_111: ${{ steps.changed.outputs.changed_workspace_111 }}
      changed_workspace_112: ${{ steps.changed.outputs.changed_workspace_112 }}
      changed_workspace_113: ${{ steps.changed.outputs.changed_workspace_113 }}
      changed_workspace_114: ${{ steps.changed.outputs.changed_workspace_114 }}
      changed_workspace_115: ${{ steps.changed.outputs.changed_workspace_115 }}
      changed_workspace_116: ${{ steps.changed.outputs.changed_workspace_116 }}
      changed_workspace_117: ${{ steps.changed.outputs.changed_workspace_117 }}
      changed_workspace_118: ${{ steps.changed.outputs.changed_workspace_118 }}
      changed_workspace_119: ${{ steps.changed.outputs.changed_workspace_119 }}
      changed_workspace_120: ${{ steps.changed.outputs.changed_workspace_120 }}
      changed_workspace_121: ${{ steps.changed.outputs.changed_workspace_121 }}
      changed_workspace_122: ${{ steps.changed.outputs.changed_workspace_122 }}
      changed_workspace_123: ${{ steps.changed.outputs.changed_workspace_123 }}
      changed_workspace_124: ${{ steps.changed.outputs.changed_workspace_124 }}
      changed_workspace_125: ${{ steps.changed.outputs.changed_workspace_125 }}
      changed_workspace_126: ${{ steps.changed.outputs.changed_workspace_126 }}
      changed_workspace_127: ${{ steps.changed.outputs.changed_workspace_127 }}
      changed_workspace_128: ${{ steps.changed.outputs.changed_workspace_128 }}
      changed_workspace_129: ${{ steps.changed.outputs.changed_workspace_129 }}
      changed_workspace_130: ${{ steps.changed.outputs.changed_workspace_130 }}
      changed_workspace_131: ${{ steps.changed.outputs.changed_workspace_131 }}
      changed_workspace_132: ${{ steps.changed.outputs.changed_workspace_132 }}
      changed_workspace_133: ${{ steps.changed.outputs.changed_workspace_133 }}
      changed_workspace_134: ${{ steps.changed.outputs.changed_workspace_134 }}
      changed_workspace_135: ${{ steps.changed.outputs.changed_workspace_135 }}
      changed_workspace_136: ${{ steps.changed.outputs.changed_workspace_136 }}
      changed_workspace_137: ${{ steps.changed.outputs.changed_workspace_137 }}
      changed_workspace_138: ${{ steps.changed.outputs.changed_workspace_138 }}
      changed_workspace_139: ${{ steps.changed.outputs.changed_workspace_139 }}
      changed_workspace_140: ${{ steps.changed.outputs.changed_workspace_140 }}
      changed_workspace_141: ${{ steps.changed.outputs.changed_workspace_141 }}
      changed_workspace_142: ${{ steps.changed.outputs.changed_workspace_142 }}
      changed_workspace_143: ${{ steps.changed.outputs.changed_workspace_143 }}
      changed_workspace_144: ${{ steps.changed.outputs.changed_workspace_144 }}
      changed_workspace_145: ${{ steps.changed.outputs.changed_workspace_145 }}
      changed_workspace_146: ${{ steps.changed.outputs.changed_workspace_146 }}
      changed_workspace_147: ${{ steps.changed.outputs.changed_workspace_147 }}
      changed_workspace_148: ${{ steps.changed.outputs.changed_workspace_148 }}
      changed_workspace_149: ${{ steps.changed.outputs.changed_workspace_149 }}
      changed_workspace_150: ${{ steps.changed.outputs.changed_workspace_150 }}
      changed_workspace_151: ${{ steps.changed.outputs.changed_workspace_151 }}
      changed_workspace_152: ${{ steps.changed.outputs.changed_workspace_152 }}
      changed_workspace_153: ${{ steps.changed.outputs.changed_workspace_153 }}
      changed_workspace_154: ${{ steps.changed.outputs.changed_workspace_154 }}
      changed_workspace_155: ${{ steps.changed.outputs.changed_workspace_155 }}
      changed_workspace_156: ${{ steps.changed.outputs.changed_workspace_156 }}
      changed_workspace_157: ${{ steps.changed.outputs.changed_workspace_157 }}
      changed_workspace_158: ${{ steps.changed.outputs.changed_workspace_158 }}
      changed_workspace_159: ${{ steps.changed.outputs.changed_workspace_159 }}
      changed_workspace_160: ${{ steps.changed.outputs.changed_workspace_160 }}
      changed_workspace_161: ${{ steps.changed.outputs.changed_workspace_161 }}
      changed_workspace_162: ${{ steps.changed.outputs.changed_workspace_162 }}
      changed_workspace_163: ${{ steps.changed.outputs.changed_workspace_163 }}
      changed_workspace_164: ${{ steps.changed.outputs.changed_workspace_164 }}
      changed_workspace_165: ${{ steps.changed.outputs.changed_workspace_165 }}
      changed_workspace_166: ${{ steps.changed.outputs.changed_workspace_166 }}
      changed_workspace_167: ${{ steps.changed.outputs.changed_workspace_167 }}
      changed_workspace_168: ${{ steps.changed.outputs.changed_workspace_168 }}
      changed_workspace_169: ${{ steps.changed.outputs.changed_workspace_169 }}
      changed_workspace_170: ${{ steps.changed.outputs.changed_workspace_170 }}
      changed_workspace_171: ${{ steps.changed.outputs.changed_workspace_171 }}
      changed_workspace_172: ${{ steps.changed.outputs.changed_workspace_172 }}
      changed_workspace_173: ${{ steps.changed.outputs.changed_workspace_173 }}
      changed_workspace_174: ${{ steps.changed.outputs.changed_workspace_174 }}
      changed_workspace_175: ${{ steps.changed.outputs.changed_workspace_175 }}
      changed_workspace_176: ${{ steps.changed.outputs.changed_workspace_176 }}
      changed_workspace_177: ${{ steps.changed.outputs.changed_workspace_177 }}
      changed_workspace_178: ${{ steps.changed.outputs.changed_workspace_178 }}
      changed_workspace_179: ${{ steps.changed.outputs.changed_workspace_179 }}
      changed_workspace_180: ${{ steps.changed.outputs.changed_workspace_180 }}
      changed_workspace_181: ${{ steps.changed.outputs.changed_workspace_181 }}
      changed_workspace_182: ${{ steps.changed.outputs.changed_workspace_182 }}
      changed_workspace_183: ${{ steps.changed.outputs.changed_workspace_183 }}
      changed_workspace_184: ${{ steps.changed.outputs.changed_workspace_184 }}
      changed_workspace_185: ${{ steps.changed.outputs.changed_workspace_185 }}
      changed_workspace_186: ${{ steps.changed.outputs.changed_workspace_186 }}
      changed_workspace_187: ${{ steps.changed.outputs.changed_workspace_187 }}
      changed_workspace_188: ${{ steps.changed.outputs.changed_workspace_188 }}
      changed_workspace_189: ${{ steps.changed.outputs.changed_workspace_189 }}
      changed_workspace_190: ${{ steps.changed.outputs.changed_workspace_190 }}
      changed_workspace_191: ${{ steps.changed.outputs.changed_workspace_191 }}
      changed_workspace_192: ${{ steps.changed.outputs.changed_workspace_192 }}
      changed_workspace_193: ${{ steps.changed.outputs.changed_workspace_193 }}
      changed_workspace_194: ${{ steps.changed.outputs.changed_workspace_194 }}
      changed_workspace_195: ${{ steps.changed.outputs.changed_workspace_195 }}
      changed_workspace_196: ${{ steps.changed.outputs.changed_workspace_196 }}
      changed_workspace_197: ${{ steps.changed.outputs.changed_workspace_197 }}
      changed_workspace_198: ${{ steps.changed.outputs.changed_workspace_198 }}
      changed_workspace_199: ${{ steps.changed.outputs.changed_workspace_199 }}

  apply:
    name: Apply (${{ fromJson(matrix.workspace).key }})
    runs-on: [self-hosted, Linux, AWS]
    timeout-minutes: ${{ inputs.apply_timeout }}

    needs: plan

    if: github.event_name != 'pull_request' && toJson(needs.plan.outputs.*) != '[]'

    permissions:
      actions: read
      contents: read
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        workspace: ${{ needs.plan.outputs.* }}

    environment: ${{ fromJson(matrix.workspace).environment }}
    concurrency: ${{ fromJson(matrix.workspace).key }}

    steps:
    - id: parse
      uses: Brightspace/terraform-workflows/actions/parse-config@v4
      with:
        # GHA's fromJson() supports comments in JSON strings which is nice from
        # an end-user perspective (e.g. naming account ids). toJson(fromJson())
        # is used in order to strip these comments out before parsing it ourselves
        config: ${{ toJson(fromJson(inputs.config)) }}

    - uses: Brightspace/third-party-actions@actions/checkout

    - name: Assume Hub Role
      uses: Brightspace/third-party-actions@aws-actions/configure-aws-credentials
      with:
        role-to-assume: arn:aws:iam::323258989788:role/hub-roles/github+${{ github.repository_owner }}+${{ github.event.repository.name }}+tfapply
        aws-region: us-east-1

    - uses: Brightspace/terraform-workflows/actions/apply@v4
      with:
        config: |
          {
            "terraform_version": "${{ inputs.terraform_version }}",
            "environment": "${{ fromJson(matrix.workspace).environment }}",
            "key": "${{ fromJson(matrix.workspace).key }}",
            "workspace_path": "${{ fromJson(steps.parse.outputs.config)[fromJson(matrix.workspace).key].workspace_path }}"
          }

    - if: ${{ !cancelled() && inputs.slack_channel != '' }}
      name: Send Slack notification
      uses: Brightspace/terraform-workflows/actions/apply/slack@v4
      with:
        slack_channel: ${{ inputs.slack_channel }}
        slack_token: ${{ secrets.D2L_SLACK_TOKEN }}
        workspace_key: ${{ fromJson(matrix.workspace).key }}
